CREATE TABLE cliente (
    i_cliente_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_nome_cliente VARCHAR2(250) NOT NULL,
    s_cpf_cliente VARCHAR2(11) NOT NULL,
    d_nascimento_cliente DATE
);

CREATE TABLE domicilio(
    i_domicilio_domicilio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    i_numero_domicilio INT NOT NULL,
    s_tipo_domicilio CHAR(1) NOT NULL,
    s_rua_domicilio VARCHAR(40) NOT NULL,
    s_regiao_domicilio VARCHAR(30) NOT NULL
);

CREATE TABLE tipocliente(
    i_tipocliente_tipocliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_desctipocliente_tipocliente VARCHAR(250) NOT NULL UNIQUE
);
