DROP TABLE cliente;

DROP TABLE tipocliente;

CREATE TABLE cliente(
    i_cliente_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_nome_cliente VARCHAR2(250) NOT NULL,
    s_cpf_cliente VARCHAR2(11) NOT NULL,
    d_nascimento_cliente DATE
);

ALTER TABLE cliente MODIFY s_cpf_cliente CHAR(11) UNIQUE;

ALTER TABLE cliente ADD i_tipo_cliente INT DEFAULT 1;

ALTER TABLE cliente DROP COLUMN i_tipo_cliente;

CREATE TABLE tipocliente(
    i_tipocliente_tipocliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_desctipocliente_tipocliente VARCHAR(250) NOT NULL UNIQUE
);

ALTER TABLE cliente ADD i_tipocliente_tipocliente INT NOT NULL;

ALTER TABLE cliente ADD CONSTRAINT fk_tipo_cliente 
    FOREIGN KEY (i_tipocliente_tipocliente) 
    REFERENCES tipocliente(i_tipocliente_tipocliente);

INSERT INTO tipocliente (s_desctipocliente_tipocliente) VALUES ('Juridico');

INSERT INTO tipocliente (s_desctipocliente_tipocliente) VALUES ('Pessoal');

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, d_nascimento_cliente, i_tipocliente_tipocliente) VALUES ('Lucas', '00000000000', DATE '2002-12-12', 2);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, i_tipocliente_tipocliente) VALUES ('Biel', '10000000000', 2);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, d_nascimento_cliente, i_tipocliente_tipocliente) VALUES ('Dudu', '20000008910', DATE '2002-03-11', 1);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, i_tipocliente_tipocliente) VALUES ('Johnn', '30000000000', 1);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, d_nascimento_cliente, i_tipocliente_tipocliente) VALUES ('Ze', '40000000000', DATE '2003-06-12', 2);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, i_tipocliente_tipocliente) VALUES ('Johnn', '50000000000', 1);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, d_nascimento_cliente, i_tipocliente_tipocliente) VALUES ('Zeca', '60000000000', DATE '2001-06-12', 2);

SELECT * FROM cliente;

SELECT * FROM tipocliente;

UPDATE cliente
SET s_nome_cliente='Lucão', s_cpf_cliente='12345678910'
WHERE i_cliente_cliente=1;

DELETE FROM cliente c
WHERE c.d_nascimento_cliente IS NOT NULL AND EXTRACT(YEAR FROM c.d_nascimento_cliente) <> 2002;

SELECT UPPER(c.s_cpf_cliente)
FROM cliente c
WHERE SUBSTR(c.s_cpf_cliente, -4) = '8910';

SELECT DISTINCT UPPER(c.s_nome_cliente)
FROM cliente c
WHERE SUBSTR(c.s_cpf_cliente, -4) = '0000';

SELECT MAX(c.i_cliente_cliente)
FROM cliente c;

INSERT INTO cliente VALUES (
    (SELECT MAX(c.i_cliente_cliente)+1 AS cliente
    FROM cliente c),
    'Pre',
    '12345678911',
    DATE '2002-06-12',
    1
);

CREATE TABLE domicilio(
    i_domicilio_domicilio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    i_numero_domicilio INT NOT NULL,
    s_tipo_domicilio CHAR(1) NOT NULL,
    s_rua_domicilio VARCHAR(40) NOT NULL,
    s_regiao_domicilio VARCHAR(30) NOT NULL
);

ALTER TABLE cliente ADD i_domicilio_domicilio CONSTRAINT fk_tipo_cliente 
    FOREIGN KEY (i_domicilio_domicilio) 
    REFERENCES domicilio(i_domicilio_domicilio);

INSERT INTO tipocliente (s_desctipocliente_tipocliente) VALUES ('Juridico');

INSERT INTO tipocliente (s_desctipocliente_tipocliente) VALUES ('Pessoal');
