DROP TABLE cliente;

DROP TABLE domicilio;

DROP TABLE tipocliente;

CREATE TABLE cliente(
    i_cliente_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_nome_cliente VARCHAR2(250) NOT NULL,
    s_cpf_cliente VARCHAR2(11) NOT NULL,
    d_nascimento_cliente DATE
);

ALTER TABLE cliente MODIFY s_cpf_cliente CHAR(11) UNIQUE;

ALTER TABLE cliente ADD i_tipo_cliente INT DEFAULT 1;

ALTER TABLE cliente DROP COLUMN i_tipo_cliente;

CREATE TABLE tipocliente(
    i_tipocliente_tipocliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_desctipocliente_tipocliente VARCHAR(250) NOT NULL UNIQUE
);

ALTER TABLE cliente ADD i_tipocliente_tipocliente INT NOT NULL;

ALTER TABLE cliente ADD CONSTRAINT fk_tipo_cliente 
    FOREIGN KEY (i_tipocliente_tipocliente) 
    REFERENCES tipocliente(i_tipocliente_tipocliente);

INSERT INTO tipocliente (s_desctipocliente_tipocliente) VALUES ('Juridico');

INSERT INTO tipocliente (s_desctipocliente_tipocliente) VALUES ('Pessoal');

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, d_nascimento_cliente, i_tipocliente_tipocliente) VALUES ('Lucas', '00000000000', DATE '2002-12-12', 2);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, i_tipocliente_tipocliente) VALUES ('Biel', '10000000000', 2);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, d_nascimento_cliente, i_tipocliente_tipocliente) VALUES ('Dudu', '20000008910', DATE '2002-03-11', 1);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, i_tipocliente_tipocliente) VALUES ('Johnn', '30000000000', 1);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, d_nascimento_cliente, i_tipocliente_tipocliente) VALUES ('Ze', '40000000000', DATE '2003-06-12', 2);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, i_tipocliente_tipocliente) VALUES ('Johnn', '50000000000', 1);

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, d_nascimento_cliente, i_tipocliente_tipocliente) VALUES ('Zeca', '60000000000', DATE '2001-06-12', 2);

SELECT * FROM cliente;

SELECT * FROM tipocliente;

UPDATE cliente
SET s_nome_cliente='Lucão', s_cpf_cliente='12345678910'
WHERE i_cliente_cliente=1;

DELETE FROM cliente c
WHERE c.d_nascimento_cliente IS NOT NULL AND EXTRACT(YEAR FROM c.d_nascimento_cliente) <> 2002;

SELECT UPPER(c.s_cpf_cliente)
FROM cliente c
WHERE SUBSTR(c.s_cpf_cliente, -4) = '8910';

SELECT DISTINCT UPPER(c.s_nome_cliente)
FROM cliente c
WHERE SUBSTR(c.s_cpf_cliente, -4) = '0000';

SELECT MAX(c.i_cliente_cliente)
FROM cliente c;

INSERT INTO cliente VALUES (
    (SELECT MAX(c.i_cliente_cliente)+1 AS cliente
    FROM cliente c),
    'Pre',
    '12345678911',
    DATE '2002-06-12',
    1
);

CREATE TABLE domicilio(
    i_domicilio_domicilio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    i_numero_domicilio INT NOT NULL,
    s_tipo_domicilio CHAR(1) NOT NULL,
    s_rua_domicilio VARCHAR(40) NOT NULL,
    s_regiao_domicilio VARCHAR(30) NOT NULL
);

ALTER TABLE cliente ADD i_domicilio_domicilio INT;

ALTER TABLE cliente ADD CONSTRAINT fk_domicilio_cliente
    FOREIGN KEY (i_domicilio_domicilio) 
    REFERENCES domicilio(i_domicilio_domicilio);

CREATE OR REPLACE TRIGGER cliente_before_update
BEFORE UPDATE OF i_domicilio_domicilio ON cliente
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    IF :NEW.i_domicilio_domicilio IS NOT NULL THEN
        SELECT COUNT(*) INTO v_count 
        FROM domicilio 
        WHERE i_domicilio_domicilio = :NEW.i_domicilio_domicilio;
        
        IF v_count = 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Não é possível atualizar a foreign key de cliente para domicílio porque o domicílio associado não existe.');
        END IF;

        IF :OLD.i_domicilio_domicilio IS NOT NULL AND :NEW.i_domicilio_domicilio != :OLD.i_domicilio_domicilio THEN
            SELECT COUNT(*) INTO v_count 
            FROM cliente c 
            WHERE c.i_domicilio_domicilio = :OLD.i_domicilio_domicilio;
            IF v_count = 0 THEN
                DELETE FROM domicilio WHERE i_domicilio_domicilio = :OLD.i_domicilio_domicilio;
            END IF;
        END IF;
    END IF;
END;

INSERT INTO domicilio (i_numero_domicilio, s_tipo_domicilio, s_rua_domicilio, s_regiao_domicilio)
VALUES (123, 'C', 'Rua das Flores', 'Centro');

INSERT INTO cliente (s_nome_cliente, s_cpf_cliente, i_tipocliente_tipocliente, i_domicilio_domicilio)
VALUES ('Fulano', '70000000000', 1, (SELECT MAX(i_domicilio_domicilio) FROM domicilio));

SELECT * FROM cliente;

UPDATE cliente
SET i_domicilio_domicilio = (SELECT MAX(i_domicilio_domicilio) FROM domicilio)
WHERE s_nome_cliente = 'Fulano';

SELECT * FROM cliente;

CREATE OR REPLACE VIEW cliente_view AS
SELECT c.s_nome_cliente, d.s_rua_domicilio, d.i_numero_domicilio, d.s_regiao_domicilio
FROM cliente c
JOIN domicilio d ON c.i_domicilio_domicilio = d.i_domicilio_domicilio;

SELECT * FROM cliente_view;

CREATE VIEW cliente AS
    SELECT i_cliente_cliente, s_cpf_cliente, EXTRACT(DAY FROM d_nascimento_cliente) AS dia_nascimento
    FROM cliente;

SELECT * FROM cliente
WHERE i_tipocliente_tipocliente IN (1, 2) AND
   (EXTRACT(MONTH FROM d_nascimento_cliente) >= 4 AND EXTRACT(MONTH FROM d_nascimento_cliente) <= 9);

SELECT c.i_cliente_cliente, c.s_nome_cliente, c.s_cpf_cliente, tc.s_desctipocliente_tipocliente
FROM cliente c
INNER JOIN tipocliente tc ON c.i_tipocliente_tipocliente = tc.i_tipocliente_tipocliente;

SELECT
    i_tipo_cliente,
    count(i_cliente_cliente) as Qtde
FROM cliente
GROUP BY i_tipo_cliente;

SELECT *
FROM cliente
ORDER BY 5;

SELECT *
FROM cliente
ORDER BY 5 DESC, 2 ASC;

SELECT *
FROM cliente
FETCH FIRST 2 ROWS ONLY;

 SELECT *
 FROM cliente
 WHERE s_nome_cliente LIKE('L%');

 SELECT *
 FROM cliente
 WHERE s_nome_cliente LIKE('____%');

CREATE OR REPLACE PROCEDURE saudar_cliente IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Olá, Cliente!');
END;

BEGIN
    saudar_cliente;
END;

CREATE OR REPLACE PROCEDURE saudar_cliente IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Olá, Cliente!');
END;

BEGIN
    saudar_cliente;
END;

CREATE OR REPLACE PROCEDURE saudar_cliente_nome (
    p_nome_cliente IN VARCHAR2
) IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Olá, ' || p_nome_cliente || '!');
END;


BEGIN
    saudar_cliente_nome('João');
END;

